### ISSUE TITLE
Alternative Approaches to Transformation

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/nasa-hyperspectral#102]
Justin's matched filter work can be divided into three parts: (i) obtaining spectra and extracting/producing a noise model (ii) construction of a whitening operator and (ii) doing matched filter computation.

This issue is for investigation of alternative approaches to robust PCA and whitening as is currently being done.  Initially the goal will be to reproduce the current (ii) using input from (i), but alternatives that do not use input form (i) (i.e. approaches that use labeled imagery) are also possible.  The focus here is to improve the performance of this operator.

**Comment by pomadchin** [comment]
Covered by #122
