### ISSUE TITLE
PRISMA Catalog

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#103]
Build up a PRISMA Catalog. We can contact (potentially) with the ASI about making the catalog of the PRISMA data. We can collaborate on building up the catalog? 

This task is to track the specific proposal to the ASI and to collaborating. 
Also may be they already have a set of endpoints that we can access through the API to crawl it and build up thew STAC catalog.

**Comment by rcheetham** [comment]
We do not have enough access to the ESA data to be able to do this.
