### ISSUE TITLE
PRISMA to COG conversion

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#104]
Invesitgate viability of the PRISMA hdf5 conversions into COGs. (It is always possible to convert imagery, how to preseve its metadata? how much of the metadata we'll loose)

**Comment by jpolchlo** [comment]
For a frame of reference, I have a Jupyter notebook that reads a PRISMA file, showing some of the idiosyncracies of the format.  The original Gist is [here](https://gist.github.com/jpolchlo/fa150870221c11f6860a00c650e26763), a binder notebook is [here](https://mybinder.org/v2/gist/jpolchlo/fa150870221c11f6860a00c650e26763/2f4613de2c6616528c608d088089c42de5c7772d?filepath=PRISMA%20tests.ipynb)
