### ISSUE TITLE
Bali Plastic Detection

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#106]
The plastic detection process that was demonstrated in a Jupyter notebook submitted with #100 needs to be applied to PRISMA data over Bali for the GPW use case.

This issue will be complete when we have a satisfactory result for PRISMA data.

**Comment by jpolchlo** [comment]
I have a Jupyter notebook that attempts a vulgar analysis based on the methodology referred to above.  Find the original Gist is [here](https://gist.github.com/jpolchlo/fa150870221c11f6860a00c650e26763), and a binder notebook of the same [here](https://mybinder.org/v2/gist/jpolchlo/fa150870221c11f6860a00c650e26763/HEAD) (for whatever reason, Github previews of notebooks appears borked).

The takeaways from this notebook as it stands now are these:
- PRISMA files are a bit weird.  The layout of the data is a bit idiosyncratic, and the pixel spectra themselves seem to have qualitative differences depending on where in the file you look (see the last image above the scratch section; PCA reveals some inconsistency of the data within a single scene)
- Robust PCA is vastly superior to classic PCA, but it's still not good enough.  We need a much more robust and intelligent means for dimension reduction to get consistent, quality results.
- Supposing that dimension reduction can be markedly improved, target detection should suffice for this purpose

Given that dimension reduction is the key to a reliable plastic detection, this work is on pause until we make progress on that front.

**Comment by jpolchlo** [comment]
Based on many varied attempts to produce a result here, with no success, it seems it is time to abandon this question.  For now.  My current operating hypotheses are that plastics make up less of the surface of Indonesian garbage dumps, and that for a 30m pixel, the plastic signal is so overwhelmed by the other signals that, when sensor noise is added, the plastic signal cannot be discerned.

A worthy follow-up to this question is to see if pan-sharpening (perhaps along the lines of the citation below) might improve the fidelity of the target detection.

Reference:
Kremezi, M., Kristollari, V., Karathanassi, V., Topouzelis, K., Kolokoussis, P., Taggio, N., Aiello, A., Ceriola, G., Barbone, E. and Corradi, P., 2021. [Pansharpening PRISMA Data for Marine Plastic Litter Detection Using Plastic Indexes](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9406795). IEEE Access, 9, pp.61955-61971.
