### ISSUE TITLE
Chemical Cloud Detection

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#107]
Given that we now have much better context regarding hyperspectral analysis, there appears to be three main analytical techniques that, if we master them, will allow us to tackle a wide array of different problems:

1. Unmixing
2. Target detection
3. Plume detection

This epic deals with work related to plume detection.  This is applicable for many topics including methane detection, shipping lane identification (by identifying sulfur compounds produced in the combustion of diesel fuel), and identification of plastics incineration sites, the latter of which is the motivating application for pursuing this area.

The underlying model for plume detection shares features with atmospheric correction, as they are both radiative transfer problems, though it's not clear if we need to solve an atmospheric correction-style problem to do plume detection.  Further investigations will be required.

**Comment by jpolchlo** [comment]
Incidentally, we may want to consider restructuring the NASA status reports to reflect the new understanding that techniques are king, and may want to take precedence over specific applications.  We have both target detection and , we ought to look for a compelling application of each technique.
