### ISSUE TITLE
Maximum Likelihood Spectrum Extraction

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/nasa-hyperspectral#125]
An interesting experiment might be to try to extract a spectrum from the (known) TPA site in Bali.  Given known landfill and known non-landfill pixels, it should be easy to do this extraction with minor modifications to the PyTorch band selection code in the repository.

A verbal discussion has taken place between myself and Justin.  The precise details are not memorialized here, but details can be added to this issue if it is helpful.  (The basic idea was to use PyTorch's optimization capability to extract the spectrum similarly to how we use optimization to improve the whitening operator.)

**Comment by jpolchlo** [comment]
Made some progress on this task.

In one [notebook](https://gist.github.com/jpolchlo/983e30c6a85b27f385ccadfbca273b86), I extracted the relevant parts of the scene, resulting in a small, full-spectrum area of interest, and two masks, one defining the target pixels, the other defining an exclusion zone around the target.

The other [notebook](https://gist.github.com/jpolchlo/03afa893ed6260a237dc3ab42d010091), intended for use on Google Colab, consumes the output of the previous notebook to attempt to learn the best spectrum to match the landfill pixels previously extracted.

Comments are welcome.

CC: @jamesmcclain

**Comment by jamesmcclain** [comment]
> Made some progress on this task.
> 
> In one [notebook](https://gist.github.com/jpolchlo/983e30c6a85b27f385ccadfbca273b86), I extracted the relevant parts of the scene, resulting in a small, full-spectrum area of interest, and two masks, one defining the target pixels, the other defining an exclusion zone around the target.
> 
> The other [notebook](https://gist.github.com/jpolchlo/03afa893ed6260a237dc3ab42d010091), intended for use on Google Colab, consumes the output of the previous notebook to attempt to learn the best spectrum to match the landfill pixels previously extracted.
> 
> Comments are welcome.
> 
> CC: @jamesmcclain

I looked over the notebooks, they look okay.  I guess the only immediate addition I would suggest is to include a graph of the original/starting target spectrum in the very last plot of the notebook.

Did you notice any gain from using the original versus the inferred spectrum?  It would be nice to see the heat-maps generated by correlating the AOI with the original target spectrum, the inferred target spectrum, and some target spectrum produced from a non-landfill control area.

**Comment by jamesmcclain** [comment]
This has been completed.
