### ISSUE TITLE
Algal Blooms spectra follow up

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#155]
In addition to what @jpolchlo wrote below, we would like to follow-up with outside contacts about the possibility of (four or more?) species specific spectra (@jcahail )

**Comment by jpolchlo** [comment]
I was noticing that some of the spectra out in the world possibly relevant to this study (phycoerythrin, e.g.) were not found in the remote sensing literature.  Some were in medical journals and the like (often in UV-VIS spectra, <1000 nm).  These spectra might be of use to you, but beware of units.  You're looking for reflectance or radiance.  Many of the spectra I saw were measured using fluorescence, which I think isn't of use here.  You may find absorbance (or some similar quantity, which may be convertible to reflectance.  I'm not sure about that, though.

Just a hand-waving argument to suggest casting a wider net and to watching your units and measured quantities as you go looking for spectra.
