### ISSUE TITLE
Develop a playground for experimenting with Nextflow

### ISSUE THREAD

**Issue by echeipesh** [azavea/nasa-hyperspectral#17]
[NextFlow](https://www.nextflow.io/) has couple of things that are attractive to this project:
- scripting language that abstracts over multiple asynchronous modules
  - supports conditionals and iterations
- supervisor enables above behavior on AWS Batch.

Its worth noting that NextFlow is not event driven and is more focused on driving an async batch job in multiple environments.
However, this type of process is still relevant of this project as it in essence it will function as a pull stream.

Docker containers used by NextFlow could/should re-use the Activator/Processor modules from our architecture.
The messages exchanged by NextFlow modules can/should follow the same schema as event processing system.

Capturing above thinking in a short ADR will be helpful for this project.

**Comment by pomadchin** [comment]
The results of this issue and #32 live here: https://github.com/pomadchin/pipeline-playground 
cc @rbreslow
