### ISSUE TITLE
Apply phycocyanin index

### ISSUE THREAD

**Issue by jpolchlo** [azavea/nasa-hyperspectral#177]
In the paper referenced below, an index to detect phycocyanin, a toxin produced by cyanobacteria, was presented.  It would be a good idea to attempt to apply this method to some real data.  This index uses three wavelengths to perform the detection which are available in ESA's MERIS (also represented in Sentinel-3).  This method can be applied to most hyperspectral data in the VNIR range as well.

Reference:
Mishra, S., & Mishra, D. R. (2014). [A novel remote sensing algorithm to quantify phycocyanin in cyanobacterial algal blooms](https://iopscience.iop.org/article/10.1088/1748-9326/9/11/114003/pdf). Environmental Research Letters, 9(11), 114003.

**Comment by jpolchlo** [comment]
A note of possible interest: in the [Sentinel-3 docs](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-3-olci/resolutions/radiometric), the 620nm band is described as capturing "sediment loading".  620nm is a key response window for phycocyanin.  This problem may suffer from some amount of confounding with sediment signals by its nature, and perhaps other cyanobacterial markers will be preferred.

**Comment by jamesmcclain** [comment]
:eye: :eye:

**Comment by jamesmcclain** [comment]
Please see https://github.com/raster-foundry/groundwork/issues/1607

**Comment by jamesmcclain** [comment]
This is being actively discussed in https://github.com/raster-foundry/groundwork/issues/1607
