### ISSUE TITLE
HSI Metadata STAC Spec

### ISSUE THREAD

**Issue by echeipesh** [azavea/nasa-hyperspectral#2]
Hyper-spectral data has some features that would be important to keep track of in the STAC metadata.
Part or all this might be covered by https://github.com/radiantearth/stac-spec/tree/master/extensions/eo

The reason you might want to capture this metadata is to automatically adjust to how to interpret the pixel values.

We should consider what metadata is already captured in the spectral curve libraries:
- https://www.usgs.gov/labs/spec-lab
- https://speclib.jpl.nasa.gov/

Known important things:
- spectral range, steps
- sensor type/name
- sensor characteristic file
- processing level: L1/L1a/L2 
- ???

This issue is to create first DRAFT evaluation / document of metadata we may want to capture.

> Task 2-2: Document Use of STAC with Hyperspectral Data
Azavea will attempt to fit available data into the existing Earth Observation STAC extension and publicize the use case among the Free and Open Source Software (FOSS) GIS community. If the existing extension falls short and does not meet the needs of the hyperspectral data and processing system, Azavea will propose an extension to STAC specific to the use case and shepherd it through the acceptance process. Azavea is a leader in the STAC community and familiar with the necessary steps to make this possible.

### Tasks: 

We decided to split this work into two parts:

- [ ] HSI Extensions specific to the product / sensor type (AVIRIS / PRISMA / LC8)
- [x] HSI Extension that is unifies common data across different sensors (accomplished by Add HSI STAC Spec description and tests #162)
  - it is considered as "done" and will be extended / modified if necessary

**Comment by pomadchin** [comment]
We decide to split this work into two parts: 
- HSI Extensions specific to the product / sensor type (AVIRIS / PRISMA / LC8)
- HSI Extension that is unifies common data across different sensors (accomplished by https://github.com/azavea/nasa-hyperspectral/pull/162)

**Comment by rcheetham** [comment]
We were unable to identify enough common attributes to organize a specification. We also don't have enough credibility to lead such an effort.
