### ISSUE TITLE
Upgrade EKS Terraform configuration

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#202]
EKS module (starting v0.18) has a significant configuration change. This PR is to track down the progress of upgrading EKS Terraform module up to the most recent.

As a part of the configuration upgrade we may drop unused Terraform components.

**Comment by pomadchin** [comment]
It is blocked now, see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1744

**Comment by pomadchin** [comment]
I'll keep it open hanging in a debt! Since we'll have to finish it later (hopefully).

**Comment by pomadchin** [comment]
https://github.com/azavea/nasa-hyperspectral/issues/222 (this issue should probably live in another repo now)

**Comment by jpolchlo** [comment]
Note that we have a new deployment that supersedes the one in this repo [here](https://github.com/azavea/kubernetes-deployment).
