### ISSUE TITLE
Review atmospheric correction software

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#26]
Spectral library elements are sampled in lab conditions (or at least well-controlled field conditions), which don't experience significant atmospheric absorption or scattering effects.  Comparing library spectra to uncorrected imagery is destined for failure, so we need to at least understand the options for atmospheric correction.  The task here is to look at the options; the completion criteria is a developed plan for adjusting raw imagery.

**Comment by jpolchlo** [comment]
Closing this in deference to #62
