### ISSUE TITLE
Find labeled HSI dataset for species identification

### ISSUE THREAD

**Issue by echeipesh** [azavea/nasa-hyperspectral#37]
At some point we're going to have to benchmark our tools, for this we're going to need some HSI imagery and "ground-truth" labels.
We are not the first people to do vegetation species identification on HSI imagery, there are some case studies out there.

This issue is to survey available studies that have gone through some kind ground-truth verification.
Possible data sources to consider:

- PRISMA
- CHRIS on PROBA
- DESI on ISS
- AVIRIS

We have tree species labels for Philadelphia area.
This issue can be fulfilled by imagery that covers Philly for that time frame.

**Comment by jpolchlo** [comment]
This issue appears to be too vague and not tied to a specific problem.  If we find a need for something like what is demanded here, we can open a new, more targeted issue in its place.
