### ISSUE TITLE
Create IAM policy to allow Franklin to ingest from aviris-data bucket

### ISSUE THREAD

**Issue by rbreslow** [azavea/nasa-hyperspectral#43]
There is a bucket in our AWS account named `aviris-data` that Franklin needs to have I/O access to.

- Determine whether Franklin needs read access, write access, or both.
- Create and attach an IAM policy, similar to https://github.com/azavea/american-water-tank-magic/blob/cb76297c734aabd13b77f1ac47df67127f5e6597/deployment/terraform/iam.tf#L31-L59.

Connects #42

**Comment by pomadchin** [comment]
Is not it already addressed? https://github.com/azavea/nasa-hyperspectral/blob/master/deployment/terraform/iam.tf#L84-L100
