### ISSUE TITLE
Implement the processing workflow using Nextflow

### ISSUE THREAD

**Issue by rbreslow** [azavea/nasa-hyperspectral#50]
We can lean on Grisha's research from the [pipeline playground](https://github.com/azavea/pipeline-playground). Also, these [AWS docs](https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview/) describe a path where there's a Batch job definition that runs a Nextflow "head job" that then spins off "task jobs."

The specific components of the workflow will become clear after #56 is complete.

**Comment by pomadchin** [comment]
Closed for the same reasons as in the issue #87
