### ISSUE TITLE
Review AVIRIS per scene metadata

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#64]
There was rised a metadata discussion in #55 and Eugene suggested to collect all possible AVIRIS metadata. 

This task is to identify what is this 'AVIRIS metadata' and how / where it is stored. 
Is all the metadata delivered in L2 scenes archives or we need to download L1 as well? 

What was highlighted by @jpolchlo is that we would need to collect bands frequences (centers of wavelengths) as it may vary per flight.

**Comment by jpolchlo** [comment]
For clarity, I am skeptical that different flights have different band wavelengths, but I can confirm that there are small differences between two scenes from 2008 and 2017.  I'm hoping that this is due to different sensor versions, and that each version has stable band center wavelengths and FWHM values.  If that is the case, we can hard code each version's profile into the STAC metadata without having to retrieve the `.spc` file from the L1 archive.  (That's contingent on being able to easily determine the sensor in use from either the scene name or the source CSV.)

**Comment by CloudNiner** [comment]
In the process of working on #55 I now have a COGified AVIRIS L2 scene. It appears that the wavelengths for each band in the tiff are provided in the metadata, but there's enough metadata that I got an `aux.xml` PAM file when the COG was written by GDAL:
```
Warning 1: /tmp/f130329t01p00r06/f130329t01p00r06_rfl/f130329t01p00r06_corr_v1.tiff: Metadata exceeding 32000 bytes cannot be written into GeoTIFF. Transferred to PAM instead.
```

This file contains the output of `gdalinfo` on the COG:
[f130329t01p00r06_corr_v1.tiff.gdalinfo.txt](https://github.com/azavea/nasa-hyperspectral/files/5643706/f130329t01p00r06_corr_v1.tiff.gdalinfo.txt)

Is this information sufficient for the purposes of this issue? Will our tooling (e.g. RasterSource) be able to read metadata contained in the xml file if I upload it with the COG?

**Comment by pomadchin** [comment]
@CloudNiner GDALRasterSource probably would be able to handle that. I'd like to suggest you to set [GDAL_PAM_ENABLED](https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_PAM_ENABLED) option to `NO` to write it as a metadata into a COG rather than spawning a separate file.

**Comment by CloudNiner** [comment]
For sure GDAL if it can automatically puts metadata in the tiff header. I think the issue here is that the metadata is too large to fit in the GeoTIFF header. The warning posted above:

> Metadata exceeding 32000 bytes cannot be written into GeoTIFF

I will try the config option you suggested, but I expect it will fail or truncate some of the metadata we need.

**Comment by pomadchin** [comment]
> Metadata exceeding 32000 bytes cannot be written into GeoTIFF 

Ooooh you're right. And the file is already 52kbs size. So mb that is not bad in this case to store it as a separate asset than. 
Good to know anyway! Thanks for digging into that.
