### ISSUE TITLE
Skip AVIRIS scenes that have already been pre-processed

### ISSUE THREAD

**Issue by CloudNiner** [azavea/nasa-hyperspectral#68]
In #55 we built the L2 Activator. At that time we decided not to include skip and return logic for an AVIRIS scene that's already been proceed. We think that this can be handled at the infrastructure level or have the task that calls this activator check to see if it needs to be run.

**Comment by pomadchin** [comment]
All activation modules already do this, in fact that was needed for all the processing done by @jamesmcclain
