### ISSUE TITLE
Label landfill areas

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#72]
This task can use results of https://github.com/azavea/nasa-hyperspectral/issues/71 to label AOIs. 

However, there are no limits / bounds of how many AOIs would be selected and labelled; if it would be neccesary it is always possibe to use [the entire GeoPackage](https://github.com/azavea/nasa-hyperspectral/issues/52#issuecomment-737428389) and select several AOIs directly from it.

I would like to see the result as a STAC Catalog, but it can be just a set of json files.

**Comment by jpolchlo** [comment]
We've somewhat moved on from the plastic detection problem underlying this issue.  What's outlined here may be of use if we were to ever want to devise a machine learning approach to automated discovery of landfills, but for now it seems this issue has outlived its usefulness.
