### ISSUE TITLE
Restructure project to be more cohesive

### ISSUE THREAD

**Issue by CloudNiner** [azavea/nasa-hyperspectral#73]
Rocky and I reviewed #69 and #65 today in an attempt to streamline the project structure.

The takeaway is this issue, which encapsulates a refactor of the code in the repo so far such that we can add additional project features without too much overhead.

We'll have:
```
./deployment
./docs
./src/catalogs
./src/hsi-lib
./src/pipeline
docker-compose.yml
```

Each dir under source can contain a Dockerfile and a README that encapsulates the docs and deps of that component and is to be referenced by docker-compose.yml.

It is unclear whether we keep the vscode dev container or transition to requiring conda to be installed on the host. We intend to discuss that at the next planning meeting and then use #48 to configure the dev environment for the result of that decision.

Depends on merging #69 and #65

**Comment by rbreslow** [comment]
I believe we discussed keeping the VSCode development container while defaulting to requiring Conda on the host. Was the intention that I'd wait for this initial refactor to be complete, and then use #48 to implement STRTA that use Conda?

**Comment by CloudNiner** [comment]
> Was the intention that I'd wait for this initial refactor to be complete, and then use #48 to implement STRTA that use Conda?

Yes. I plan to preserve the vscode dev container in this issue. If that doesn't work out, we can iterate when that happens.
