### ISSUE TITLE
Add AVIRIS-ng to Franklin

### ISSUE THREAD

**Issue by jpolchlo** [azavea/nasa-hyperspectral#79]
AVIRIS and AVIRIS-ng are cataloged separately by JPL/NASA.  The latter has more international flights, and half the FWHM of AVIRIS classic (and zero calories!).  The source table is here: https://docs.google.com/spreadsheets/d/1v6VoBodTqPdhAZ9Goc4vhpwVLew8KGfYyLJDqb151pI/edit#gid=1403228846

I can confirm that all our existing tools should work for this, but the FTP server seems a bit touchier.  Beware.  We may want to add a `is_ng` property?  Or just add this to a separate table?  Better's choice.

**Comment by pomadchin** [comment]
AVIRIS NG Data Portal https://avirisng.jpl.nasa.gov/dataportal/
