### ISSUE TITLE
Contribute STAC Client to stac4s

### ISSUE THREAD

**Issue by CloudNiner** [azavea/nasa-hyperspectral#80]
We need a STAC Client for #56. There is a work in progress PR to provide one to the stac4s library at https://github.com/azavea/stac4s/pull/140.

To complete that PR, we'd like to:
- Migrate blaze client to sttp backend
- Add write functions to STAC Client trait (POST Collection, POST Collection Item)
- Any cleanup required based on changes to STAC spec for latest stac version

**Comment by CloudNiner** [comment]
Extension to `trait StacClient` probably looks something like:
```scala
def createItem(collectionId: NonEmptyString, item: StacItem): F[StacItem]
def createCollection(collection: StacCollection): F[StacCollection]
```

**Comment by CloudNiner** [comment]
Consider supporting scala.js as well. @jisantuc thinks:

> since the js and jvm core modules have all the same STAC types, you might be able to throw everything into shared/ and things should Just Work :tm:?

If that works, great, but our focus here is a working scala client so if that's as far as we get with this issue that's fine.

**Comment by pomadchin** [comment]
@CloudNiner agree, ScalaJS can take another 8hrs.

**Comment by pomadchin** [comment]
I'll close this one once we'll publish the stac4s client module.

**Comment by jisantuc** [comment]
It's published, waiting for Maven

**Comment by pomadchin** [comment]
@jisantuc hmm I can't see `0.0.20` release, only [0.0.19-9-g517278d](https://repo1.maven.org/maven2/com/azavea/stac4s/client_2.12/0.0.19-9-g517278d/).

But anyway, closing this issue for now, since there is at least this release!

**Comment by jisantuc** [comment]
Ugh you're right I'll fix that, one moment please.

**Comment by jisantuc** [comment]
In progress here: https://app.circleci.com/pipelines/github/azavea/stac4s/560/workflows/edcfb106-dfee-4260-a94c-c613fb7bd52b/jobs/633

**Comment by pomadchin** [comment]
@jisantuc thanks for keeping track of that! `0.0.20` release is there! cc @CloudNiner
