### ISSUE TITLE
Deliver an evaluation that compares Nextflow and Step Functions

### ISSUE THREAD

**Issue by rbreslow** [azavea/nasa-hyperspectral#87]
We are going to implement a production-grade version of our image processing pipeline using both Nextflow (#50) and Step Functions (#53). 

Once there are pull requests up for both variants, we'll assemble a document that attempts to discern how they compare with one another. And then, we'll make a final decision to merge one of the implementations.

**Comment by pomadchin** [comment]
We have separate comparison documents for StepFunctions, Nextflow, Kubeflow and Argo Workflows that live here https://github.com/azavea/pipeline-playground

After trying Argo Workflows and taking into account ML Engineers interest in Kubeflow I'm going just to close this issue.
