### ISSUE TITLE
Use layers extension in generated STAC catalogs

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#93]
At this point we have multiple collections. An each collection represents a separate `layer`. 
However, I'd like to generalize collections a bit further. 
This task is to add `layer:ids` property into all generated items according to the [Layer STAC Extension spec](https://github.com/azavea/stac4s/tree/master/docs/stac-spec/extensions/layer).

Its usage example is shown below:
```javascript
{
    "id" : "id",
    "stac_extensions" : ["layer"],
    // ...
    "properties": {
        "collection": "item-collection",
        "layer:ids" : ["layer-us", "layer-pa"]
    }
    // ...
}
```

It may seem a bit preamture, but it can simplify visualization of the STAC catalog #60

**Comment by CloudNiner** [comment]
Adding this in #89 was requested [here](https://github.com/azavea/nasa-hyperspectral/pull/89#pullrequestreview-564607841). Is the request to just add a single layer id that matches the collection name for now? Does that actually provide value over just using the STAC API Query endpoint to filter by collection property name? Is there some other layer id that would be preferable to use?

**Comment by pomadchin** [comment]
The whole value is in providing filtering by the property name and this will give us full compact with the GT server (https://github.com/azavea/nasa-hyperspectral/issues/60). Do you think it's premature?

**Comment by CloudNiner** [comment]
Sorry, I'm not sure what your comment is saying. The request in #89 was to add a layer-id for a given item that matches the collection name of the item. That feels redundant when it's possible to just query by the collection name so I don't see what making that change buys us. Are there other properties, like flight id, year, month, day, etc that would be more useful to write as layer ids? If we don't know yet perhaps we should just hold off on this task.

**Comment by pomadchin** [comment]
@CloudNiner GT Server operates with `layers`; it is a seamless integration with it requiring no code writing.

**Comment by CloudNiner** [comment]
Ah ok, that wasn't clear from the link in your last comment. I can just do layer id matching collection for now.

**Comment by pomadchin** [comment]
@CloudNiner :+1:
